#!/usr/bin/env ruby

require 'fileutils'

if ARGV.count != 2
  puts "usage: start METRONIC DIRECTORY RAILS APP DIRECTORY"
  puts "install metronic theme into the specified rails app"

  exit 1
end

metronic_directory = ARGV[0]
rails_app_directory = ARGV[1]

if !Dir.exists?(metronic_directory)
  puts "#{metronic_directory} doesn't exist"
  exit 1
end

if !Dir.exists?(rails_app_directory)
  puts "#{rails_app_directory} doesn't exist"
  exit 1
end

puts "copy Admin 1 rounded dark blue theme"

puts "** copy font-awesome"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

FileUtils.cp_r(
  File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/fonts/'),
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

font_awesome_css = File.read(File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'))
File.open(File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'), 'w') do |f|
  f.write(font_awesome_css.gsub("url('../fonts", "url('fonts"))
end

puts "** copy simple line icons"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/simple-line-icons/', 'simple-line-icons.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

FileUtils.cp_r(
  File.join(metronic_directory, 'theme/assets/global/plugins/simple-line-icons/fonts/'),
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "** bootstrap"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap/css', 'bootstrap.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "** uniform"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/uniform/css', 'uniform.default.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "** bootstrap-switch"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap-switch/css/', 'bootstrap-switch.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "rounded components"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/css/', 'components-rounded.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "plugins"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/css/', 'plugins.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "layout 1"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/layouts/layout/css/', 'layout.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "darkblue"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/layouts/layout/css/themes/', 'darkblue.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "Javascripts"

puts "** bootstrap"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap/js/', 'bootstrap.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/', 'js.cookie.min.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap-hover-dropdown/', 'bootstrap-hover-dropdown.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

        # <script src="../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        # <script src="../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        # <script src="../assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        # <script src="../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>