#!/usr/bin/env ruby

require 'fileutils'

if ARGV.count != 2
  puts "usage: start METRONIC DIRECTORY RAILS APP DIRECTORY"
  puts "install metronic theme into the specified rails app"

  exit 1
end

metronic_directory = ARGV[0]
rails_app_directory = ARGV[1]

if !Dir.exists?(metronic_directory)
  puts "#{metronic_directory} doesn't exist"
  exit 1
end

if !Dir.exists?(rails_app_directory)
  puts "#{rails_app_directory} doesn't exist"
  exit 1
end

puts "copy Admin 1 rounded dark blue theme"

puts "copy font-awesome"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

FileUtils.cp_r(
  File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/fonts/'),
  File.join(rails_app_directory, 'vendor/assets/stylesheets/fonts/'))


