#!/usr/bin/env ruby

require 'fileutils'
require 'optparse'
require 'ostruct'

options = OpenStruct.new
options.theme_color = :default
options.source = ""
options.destination = ""

OptionParser.new do |opts|
  opts.banner = "Usage: start [options]"
  
  opts.on("-s", "--source DIRECTORY", "Metronic directory") do |v|
    options.source = v
  end
  
  opts.on("-d", "--destination DIRECTORY", "Rails application directory") do |v|
    options.destination = v
  end

  colors = [:default, :darkblue, :blue, :grey, :light, :light2]
  opts.on("-c", "--theme-color [COLOR]", colors, "Theme color (#{colors.join(", ")})") do |v|
    options.theme_color = v
  end
end.parse!

metronic_directory = options.source
rails_app_directory = options.destination

if !Dir.exists?(metronic_directory)
  puts "#{metronic_directory} doesn't exist"
  exit 1
end

if !Dir.exists?(rails_app_directory)
  puts "#{rails_app_directory} doesn't exist"
  exit 1
end

puts "copy Admin 1 rounded #{options.theme_color} theme"

puts "** copy font-awesome"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

FileUtils.cp_r(
  File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/fonts/'),
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

font_awesome_css = File.read(File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'))
File.open(File.join(metronic_directory, 'theme/assets/global/plugins/font-awesome/css', 'font-awesome.css'), 'w') do |f|
  f.write(font_awesome_css.gsub("url('../fonts", "url('fonts"))
end

puts "** copy simple line icons"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/simple-line-icons/', 'simple-line-icons.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

FileUtils.cp_r(
  File.join(metronic_directory, 'theme/assets/global/plugins/simple-line-icons/fonts/'),
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "** bootstrap"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap/css', 'bootstrap.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "** uniform"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/uniform/css', 'uniform.default.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "** bootstrap-switch"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap-switch/css/', 'bootstrap-switch.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "rounded components"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/css/', 'components-rounded.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "plugins"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/css/', 'plugins.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "layout 1"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/layouts/layout/css/', 'layout.css'), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "darkblue"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/layouts/layout/css/themes/', "#{options.theme_color}.css"), 
  File.join(rails_app_directory, 'vendor/assets/stylesheets/'))

puts "Javascripts"

puts "** bootstrap and jquery plugins"

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap/js/', 'bootstrap.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/', 'js.cookie.min.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap-hover-dropdown/', 'bootstrap-hover-dropdown.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/jquery-slimscroll/', 'jquery.slimscroll.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/', 'jquery.blockui.min.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/uniform/', 'jquery.uniform.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))

FileUtils.cp(
  File.join(metronic_directory, 'theme/assets/global/plugins/bootstrap-switch/js/', 'bootstrap-switch.js'), 
  File.join(rails_app_directory, 'vendor/assets/javascripts/'))